version: '3.1'
services:
  db:
    image: postgres
    restart: always
    tty: true
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mmorpg
    ports:
      - "5432:5432"
  frontend:
    tty: true
    restart: always
    build:
      context: ./docker/frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/frontend
      - /node_modules
  www:
    tty: true
    restart: always
    build:
      context: ./docker/backend/www
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/backend
      - /node_modules
    depends_on:
      - db
  game:
    tty: true
    restart: always
    build:
      context: ./docker/backend/game
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/backend
      - /node_modules
    depends_on:
      - db
